### ISSUE TITLE
addressName not getting updated when onBlur event occurs

### ISSUE THREAD

**Issue by leKg1** [leKg1/Crypto-account-statement-tool#1]
After editing addressName in the table onBlur event occurs:

1) first at Transaction.js 268 and 288 updateAddressInMoralis is called which also calls queryAddressBookFromMoralis and check if the address related to addressName exist in moralis database then addressName get updated if not add a new address as key and addressName as value. 

2) After updateAddressInMoralis the useEffect at Transaction.js 146 which read the complete addressbook from moralis database and set the local state ourLocalMoralisAddresses with data is also triggered, but at this step it seems that the updated addressName is not queried from moralis.

3) Next the local state ourLocalMoralisAddresses at Transaction.js 271 and 291 is filled with new map (address as key and e.target.value as value) which should  trigger a re-render and re-execute useEffect.

So in fact the useEffect which reads the transactions and display in the table is getting re-executed and addressName in the table is not getting updated

![Screenshot 2021-11-08 at 18 56 47](https://user-images.githubusercontent.com/51248347/140754555-0515d0a1-203c-476d-88a6-851e3c48a60e.png)
![Screenshot 2021-11-08 at 15 12 02](https://user-images.githubusercontent.com/51248347/140734310-37e429e5-fbce-477a-b685-f185eb5ea9c9.png)
![Screenshot 2021-11-08 at 15 12 35](https://user-images.githubusercontent.com/51248347/140734312-9599edbf-dc15-446c-b865-f8ec3858a40e.png)
![Screenshot 2021-11-08 at 16 32 09](https://user-images.githubusercontent.com/51248347/140734839-d43d0e62-089e-4757-a185-fa3e3a37ea5b.png)

**Comment by inspiraluna** [comment]
So you claim, when the table gets re-rendered the map in ourLocalMoralisAddresses has the correct values but the defaultValue does not show it? 

Can present this in a video where you record your screen and hold at the necessary break points?  
Can you post this video here?

**Comment by leKg1** [comment]
https://user-images.githubusercontent.com/51248347/140930075-559734bd-88fe-483c-a1b8-d7465c64ee82.mp4

In this video you can see that at the beginning the map in ourLocalMoralisAddresses doesn't have the correct value, and after the useEffect which reads the transactions and display in the table is getting re-executed we see the correct value in ourLocalMoralisAddresses but the defaultValue does not show it as it should in all places

**Comment by leKg1** [comment]
I will close this issue since it has been fixed here: https://github.com/leKg1/Crypto-account-statement-tool/commit/292ccdf6db900eaf2a52307fcf73aab0c5cd8130#diff-fc7b53a4e5766cb3b819e7b21574d2b702457a372ddd8a5d9a18e6f1a4ca88f6R245-R356

**Comment by leKg1** [comment]
I will close this issue since it has been fixed here:  https://github.com/leKg1/Crypto-account-statement-tool/commit/292ccdf6db900eaf2a52307fcf73aab0c5cd8130#diff-fc7b53a4e5766cb3b819e7b21574d2b702457a372ddd8a5d9a18e6f1a4ca88f6R245-R356
